apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: project-staging

images:
- name: PROJECT/BACKEND
  newName: raihhardv/todo-backend
  newTag: 06668cc957ea66f4553e3aec364a77ad54b27c58
- name: PROJECT/FRONTEND
  newName: raihhardv/todo-frontend
  newTag: 06668cc957ea66f4553e3aec364a77ad54b27c58
