apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: project-staging

images:
- name: PROJECT/BACKEND
  newName: raihhardv/todo-backend
  newTag: f191f817c0ed049b2a4a0d8e534126a9e6afe7e7
- name: PROJECT/FRONTEND
  newName: raihhardv/todo-frontend
  newTag: f191f817c0ed049b2a4a0d8e534126a9e6afe7e7
