apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: project-staging

images:
- name: PROJECT/BACKEND
  newName: raihhardv/todo-backend
  newTag: b0e1ab1ef3b09bdd7a2f5242a1b487be6be2333c
- name: PROJECT/FRONTEND
  newName: raihhardv/todo-frontend
  newTag: b0e1ab1ef3b09bdd7a2f5242a1b487be6be2333c
