apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: project-production

images:
- name: PROJECT/BACKEND
  newName: raihhardv/todo-backend
  newTag: c7ccb185897a039dc8753cb4adea4264f19187c7
- name: PROJECT/FRONTEND
  newName: raihhardv/todo-frontend
  newTag: c7ccb185897a039dc8753cb4adea4264f19187c7
