apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: project-production

images:
- name: PROJECT/BACKEND
  newName: raihhardv/todo-backend
  newTag: b0f40772c9ce9b5aace3f60677f46b4c3bbbd94f
- name: PROJECT/FRONTEND
  newName: raihhardv/todo-frontend
  newTag: b0f40772c9ce9b5aace3f60677f46b4c3bbbd94f
