apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: project-production

images:
- name: PROJECT/BACKEND
  newName: raihhardv/todo-backend
  newTag: 7d08a3a7635d26736fcf740b1d609ffd70e81150
- name: PROJECT/FRONTEND
  newName: raihhardv/todo-frontend
  newTag: 7d08a3a7635d26736fcf740b1d609ffd70e81150
