apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./statefulset.yaml
- ./deployment-backend.yaml
- ./deployment-frontend.yaml
- ./ingress.yaml
#  - ./manifests/backup-cronjob.yaml
images:
- name: PROJECT/BACKEND
  newName: raihhardv/todo-backend
  newTag: 876e7bb1b8ae242156b0a7efea6f76d9dc7a8a77
- name: PROJECT/FRONTEND
  newName: raihhardv/todo-frontend
  newTag: 876e7bb1b8ae242156b0a7efea6f76d9dc7a8a77
